### ISSUE TITLE
LTC: bus error (many times tested) with gdb backtrace

### ISSUE THREAD

**Issue by ghost** [jl777/SuperNET#117]
Launched gdb ../agents/iguana, then "run":
Ended with:

Thread 16 "iguana" received signal SIGBUS, Bus error.
[Switching to Thread 0x7fffe769a700 (LWP 4534)]
0x000000000043bc88 in iguana_bundletx (coin=0x7fffcec14010, bp=0x7fffc1390630, bundlei=0, 
    tx=0x7fffe7698f10, txidind=1) at iguana_bundles.c:426
426	        T = RAMCHAIN_PTR(rptr,Toffset);

GDB Backtrace:

(gdb) backtrace
#0  0x000000000043bc88 in iguana_bundletx (coin=0x7fffcec14010, bp=0x7fffc1390630, bundlei=0, 
    tx=0x7fffe7698f10, txidind=1) at iguana_bundles.c:426
#1  0x00000000004c2d68 in iguana_blocktx (coin=coin@entry=0x7fffcec14010, 
    tx=tx@entry=0x7fffe7698f10, block=block@entry=0x7fffc13ae170, i=i@entry=0) at iguana_tx.c:161
#2  0x00000000004c358f in iguana_peerblockrequest (myinfo=myinfo@entry=0x81ace0 <MYINFO>, 
    coin=coin@entry=0x7fffcec14010, blockspace=blockspace@entry=0x7fffd80008c0 "", 
    max=max@entry=4202496, addr=addr@entry=0x0, hash2=..., validatesigs=validatesigs@entry=1)
    at iguana_tx.c:275
#3  0x00000000004befd6 in iguana_bundlevalidate (myinfo=0x81ace0 <MYINFO>, coin=0x7fffcec14010, 
    bp=0x7fffc1390630, forceflag=<optimized out>) at iguana_spendvectors.c:1179
#4  0x0000000000430a12 in iguana_helper (arg=0x3dcf0f0) at iguana777.c:766
#5  0x000000000052a7db in iguana_launcher ()
#6  0x00007ffff795470a in start_thread (arg=0x7fffe769a700) at pthread_create.c:333
#7  0x00007ffff738182d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by ghost** [comment]
Different result after different updates:
Lines like this:

rw.1 numvins.1 numvouts.1 error generating txbytes txid bdc37470bde58ea56a1ca58cfb9f2d80fe5d240dd6a0650a6946594369b6bb79 vs fae64833ef63a23b7ba4f4746a8be9ae002a53ef6dfd72b60b74c356dba1ee79
01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff0f041ee3844f024409062f503253482fffffffff0100f2052a010000000000000000

Then after like this:

rw.1 numvins.1 numvouts.1 error generating txbytes txid 97777d7044f568ca05a67ce5435e58c25c6c0e723d52a8704d101644f3f4d2b3 vs 7e14bd4710e7bb877b9e472b92e9848af03f9e97abf096884de7af6472fd93ed
LTC NOT VALIDATED.[57] ht.114000 duration.1 errs.1072 total.785169 0 | total errs.7047 validated.89264 bbc30e37370cb4fc
LTC remove.[57]
LTC delete bundle.[57]
error validating.[57], restart iguana
[Thread 0x7fffc9b8a700 (LWP 11245) exited]
[Thread 0x7fffca38b700 (LWP 11244) exited]

Thread 0x.......... lines continue for a while and:
(gdb) backtrace results in:
No stack.

**Comment by jl777** [comment]
does master branch have these issues?

**Comment by ghost** [comment]
LTC goes to RT in master.
